### ISSUE TITLE
[1.19.2] Game launches but says an error has occured with Nature's Aura

### ISSUE THREAD

**Issue by Pandaw15** [Ellpeck/NaturesAura#303] opened 2023-03-19 16:10 UTC
Hi! I'm remaking my modpack but in 1.19.2, and it seems like Nature's Aura is having a problem during the mod loading ? I'm using forge 43.2.7 with Nature's Aura 38.0.

Here's the crash log: https://pastebin.com/QEqg2C6a

And here's part of the log that may reference the issue ("Caught exception during event FMLCommonSetupEvent dispatch for modid naturesaura"): https://pastebin.com/gAA1CJtu

Just for clarity, of all +300 mods, surprisingly, Nature's aura's the only problem, it launches normally without it (I also disabled Nature's Aura Tweaker just in case but I haven't seen any mention of it anyway); I guess it may still be a compatibility issue, but you'll know better.

**Comment by 4RealHaxt0rZ** [comment] 2023-04-15 13:32
I'm having the same problem after I uninstalled the Tool Belt mod, so I reinstalled it, and I'm still having this error

**Comment by Ellpeck** [comment] 2023-04-15 14:05
This looks like a duplicate of #306

**Closed by Ellpeck** 2023-04-15 14:05 UTC
