### ISSUE TITLE
crash found when launching pack

### ISSUE THREAD

**Issue by Warbringer12** [Ellpeck/NaturesAura#112] opened 2020-05-04 02:40 UTC
[crash-2020-05-03_19.32.05-client.txt](https://github.com/Ellpeck/NaturesAura/files/4572580/crash-2020-05-03_19.32.05-client.txt)

Caused by: java.lang.ClassNotFoundException: de.ellpeck.naturesaura.api.recipes.ing.AmountIngredient
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.1.0.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {} from lastest log

**Comment by Ellpeck** [comment] 2020-05-04 10:01
Duplicate of #111

**Comment by Ellpeck** [comment] 2020-05-04 10:02
duplicate of #109.

**Closed by Ellpeck** 2020-05-04 10:02 UTC
