### ISSUE TITLE
Server Crashes when I break the ancient saplings leaves.

### ISSUE THREAD

**Issue by draco7858** [Ellpeck/NaturesAura#87] opened 2020-03-05 03:33 UTC
I was playing on my friends Atm5 server, and I grew the ancient sapling and there were no problems, however, when I broke one leaf, the rest of the leaves dissipated, and the server crashed, not too sure why

**Comment by Ellpeck** [comment] 2020-03-05 09:58
Duplicate of #82

**Closed by Ellpeck** 2020-03-05 09:58 UTC
