### ISSUE TITLE
Canopy Diminisher interaction with BYG trees

### ISSUE THREAD

**Issue by pafeuu** [Ellpeck/NaturesAura#244] opened 2022-02-23 21:17 UTC
Hey I dont know if its really possible to fix but BYG adds some new tree variants to the vanilla saplings which are much bigger, unfortunately they seem to grow even with canopy diminisher around

**Comment by Ellpeck** [comment] 2022-02-23 21:19
Duplicate of #236

**Closed by Ellpeck** 2022-02-23 21:19 UTC
