### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by SgtBoom** [Ellpeck/NaturesAura#113] opened 2020-05-06 15:14 UTC
Hello, I'm getting a crash on startup. I believe that I have the latest version of the mod and Patchouli installed. Also, there are minimal mods installed. Thanks for the help!

https://pastebin.com/rpLci6Wa

**Comment by Ellpeck** [comment] 2020-05-06 15:15
Duplicate of #112

**Closed by Ellpeck** 2020-05-06 15:15 UTC
