### ISSUE TITLE
Altar Item Input

### ISSUE THREAD

**Issue by Fortist** [Ellpeck/NaturesAura#32] opened 2019-02-18 13:05 UTC
While testing, I realized how finicky the Altar is.
Iron can be right clicked right in.
Rotten Flesh cannot.
Any blocks are placed for a split second and then placed into the altar. (Like if you open a buggy chest from a mod with a placeable block in hand, the block is placed for a second before disappearing and you open the GUI.)
Only when using item transportation of sorts, it just works.

**Comment by Ellpeck** [comment] 2019-02-18 13:06
Duplicate of #30

**Closed by Ellpeck** 2019-02-18 13:07 UTC
