### ISSUE TITLE
Nothing happens when I use the Eye of the Blaze

### ISSUE THREAD

**Issue by aaronhowser1** [Ellpeck/NaturesAura#270] opened 2022-09-05 10:59 UTC
![image](https://user-images.githubusercontent.com/15698722/188433697-3261a91a-32dd-43d4-9e5e-2c5652d460df.png)

I'm right-clicking and nothing is happening

This is on 1.18, using NaturesAura-36.2

**Comment by aaronhowser1** [comment] 2022-09-05 11:00
Possibly related to #269 ?

**Comment by Ellpeck** [comment] 2022-09-15 13:50
This is a duplicate of #269

**Closed by Ellpeck** 2022-09-15 13:50 UTC
Labels: bug
