### ISSUE TITLE
[1.15.2]Server crash

### ISSUE THREAD

**Issue by EnterFor** [Ellpeck/NaturesAura#102] opened 2020-04-04 12:15 UTC
I don't know how it happens
[crash-2020-04-04_20.13.00-server.txt](https://github.com/Ellpeck/NaturesAura/files/4431303/crash-2020-04-04_20.13.00-server.txt)

**Comment by EnterFor** [comment] 2020-04-04 12:17
One player said they destroyed a leaf whose name they couldn't remember

**Comment by Ellpeck** [comment] 2020-04-04 12:20
Duplicate of #98

**Closed by Ellpeck** 2020-04-04 12:20 UTC
