### ISSUE TITLE
Advancement "Gear up intensifies" doesn't complete

### ISSUE THREAD

**Issue by Venom31** [Ellpeck/NaturesAura#142] opened 2020-09-12 19:29 UTC
Nature's Aura 28.2
Minecraft 1.15.2
Forge 31.2.9

The advancement says "Create an Infused Iron Pickaxe and Blade". Pickaxe and sword made of Infused Iron are called Botanist's Pickaxe and Blade. Crafting them does not give the player that advancement, therefore preventing (?) player from unlocking some book entry(ies?).

**Comment by Ellpeck** [comment] 2020-09-23 21:25
Cannot reproduce. Please try to reproduce this without any other mods installed.

**Comment by Venom31** [comment] 2020-09-25 19:30
If it works on pure installation, perhaps it's some mod interaction/conflict. FTB Omnia (where I've seen this) has ~100 mods. That will take some time to figure out...

**Comment by Ellpeck** [comment] 2020-10-18 15:34
Closing this for now, but if you find the culprit, you can reopen this issue or report to the respective repository.

**Closed by Ellpeck** 2020-10-18 15:34 UTC
