### ISSUE TITLE
unsure if serious or not, getting a number of repeated naturesaura recipe(?) big error traces in log

### ISSUE THREAD

**Issue by hiimrickross** [Ellpeck/NaturesAura#344] opened 2024-02-01 09:48 UTC
hi, while looking thru logs / hunting crashes for other things, i noticed there is big sections of recipe failures for naturesaura in there.
[sophisticatednaturesalexcaves.txt](https://github.com/Ellpeck/NaturesAura/files/14123211/sophisticatednaturesalexcaves.txt)

is this inconsequential, or might cause problems?

**Comment by Ellpeck** [comment] 2024-03-07 14:08
Hi! Does this also happen with just Nature's Aura and Patchouli installed?

**Comment by AndreAugustoDev** [comment] 2024-03-11 16:54
This issue might be caused by these functions above
The `JEINaturesAuraPlugin.registerItemSubtypes#registration.registerSubtypeInterpreter` definition doesn't check if the return value of getEffect can be null.
The return value of `ItemEffectPowder.getEffect` can indeed be null.
`JEINaturesAuraPlugin.registerItemSubtypes#registration.registerSubtypeInterpreter` doesn't know how to correct handle a null return value.
It seems that the return value of `ItemEffectPowder.getEffect` is null, and `JEINaturesAuraPlugin.registerItemSubtypes#registration.registerSubtypeInterpreter` is unable to process this.

https://github.com/Ellpeck/NaturesAura/blob/f2547e6555f40ae8a5d2ad5f1bc9c379dc5e50ff/src/main/java/de/ellpeck/naturesaura/items/ItemEffectPowder.java#L24-L31

https://github.com/Ellpeck/NaturesAura/blob/f2547e6555f40ae8a5d2ad5f1bc9c379dc5e50ff/src/main/java/de/ellpeck/naturesaura/compat/jei/JEINaturesAuraPlugin.java#L48-L60

**Comment by Ellpeck** [comment] 2024-10-20 09:56
This turns out to have been a duplicate of #363!

**Closed by Ellpeck** 2024-10-20 09:56 UTC
Labels: bug, question
