### ISSUE TITLE
Blame Report 

### ISSUE THREAD

**Issue by ModernGamingWorld** [Ellpeck/NaturesAura#188] opened 2021-01-28 07:46 UTC
****************** Blame Report 1.9.2 ******************

 This is an experimental report. It is suppose to automatically read
 the JSON of all the unregistered ConfiguredFeatures, ConfiguredStructures,
 and ConfiguredCarvers. Then does its best to collect the terms that seem to
 state whose mod the unregistered stuff belongs to.

Possible mods responsible for unregistered stuff:

naturesaura:aura_bloom
naturesaura:aura_cactus
naturesaura:crimson_aura_mushroom
naturesaura:warped_aura_mushroom

[28Jan2021 00:50:49.337] [main/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Report 1.9.2 ******************

 This ConfiguredFeature was found to be not registered. Look at the JSON info and try to
 find which mod it belongs to. Then go tell that mod owner to register their ConfiguredFeature
 as otherwise, it will break other mods or datapacks that registered their stuff.

 JSON info : {
  "config": {
    "feature": {
      "config": {},
      "type": "naturesaura:aura_cactus"
    },
    "decorator": {
      "config": {},
      "type": "minecraft:nope"
    }
  },
  "type": "minecraft:decorated"
}

 Biome affected : [byg:lush_red_desert, minecraft:desert, byg:red_desert, byg:oasis, minecraft:desert_hills, byg:canyon_edge, byg:mojave_desert,
                   byg:shrublands, byg:dunes, byg:canyons, byg:red_desert_dunes, minecraft:desert_lakes]

**Comment by ModernGamingWorld** [comment] 2021-01-28 07:50
[28Jan2021 00:50:49.335] [main/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Report 1.9.2 ******************

 This ConfiguredFeature was found to be not registered. Look at the JSON info and try to
 find which mod it belongs to. Then go tell that mod owner to register their ConfiguredFeature
 as otherwise, it will break other mods or datapacks that registered their stuff.

 JSON info : {
  "config": {
    "feature": {
      "config": {},
      "type": "naturesaura:warped_aura_mushroom"
    },
    "decorator": {
      "config": {},
      "type": "minecraft:nope"
    }
  },
  "type": "minecraft:decorated"
}

**Comment by Ellpeck** [comment] 2021-01-28 20:31
Duplicate of #163

**Closed by Ellpeck** 2021-01-28 20:31 UTC
