### ISSUE TITLE
Crash java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by MrEizy** [Ellpeck/NaturesAura#307] opened 2023-04-16 11:23 UTC
Latest natures aura update 38.0

[crash-2023-04-16_13.19.59-client.txt](https://github.com/Ellpeck/NaturesAura/files/11242108/crash-2023-04-16_13.19.59-client.txt)

**Comment by Ellpeck** [comment] 2023-04-16 11:27
Duplicate of #305

**Closed by Ellpeck** 2023-04-16 11:27 UTC
