### ISSUE TITLE
 de.ellpeck.naturesaura.blocks.BlockDecayedLeaves cannot be cast to net.minecraft.block.LeavesBlock

### ISSUE THREAD

**Issue by nolimet** [Ellpeck/NaturesAura#82] opened 2020-02-22 15:50 UTC
```
java.lang.ClassCastException: de.ellpeck.naturesaura.blocks.BlockDecayedLeaves cannot be cast to net.minecraft.block.LeavesBlock
	at net.olafkeijsers.fastleafdecay.FldScheduler.tick(FldScheduler.java:55) ~[?:v20] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:119) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191] {}
```
[crash-2020-02-22_16.45.46-server.txt](https://github.com/Ellpeck/NaturesAura/files/4239559/crash-2020-02-22_16.45.46-server.txt)
crash log aswell it crashed directly after the player joined

**Comment by Ellpeck** [comment] 2020-02-22 15:56
Duplicate of #78

**Closed by Ellpeck** 2020-02-22 15:56 UTC
