### ISSUE TITLE
Can't craft anceint tree saplings using the latest version of natures aura ~ The ritual just dosn't work. 

### ISSUE THREAD

**Issue by JACOBFRANTZ** [Ellpeck/NaturesAura#36] opened 2019-02-24 17:34 UTC
Can't craft anceint tree saplings using the latest version of natures aura ~ The ritual just dosn't work. 

Others using the same pack had the same issue; Some details: 

The entire structure is complete (all the blocks and items are accounted for) 

I tried growing the tree using bonemeal, and another time just by waiting. It dosn't work. 

Other rituals (Token of joy is what I tested) seem to work fine

**Comment by Ellpeck** [comment] 2019-02-24 17:35
Duplicate of #34

**Comment by Quarris** [comment] 2019-02-24 17:35
Probably a clone of #34 Try adding a sugar cane to the recipe on any of the stands to see if it works

**Closed** 2019-02-24 17:35 UTC
