### ISSUE TITLE
Server crash in 1.16.4 when dispensing ender pearl

### ISSUE THREAD

**Issue by olee** [Ellpeck/NaturesAura#172] opened 2020-12-28 20:32 UTC
This was the crashlog:
```
net.minecraft.crash.ReportedException: Exception while ticking 
  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?] 
  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] 
  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] 
  at net.minecraft.server.MinecraftServer.func_240802v(MinecraftServer.java:641) ~[?:?] 
  at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] 
  at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] 
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.item.EnderPearlEntity.<init>(Lnet/minecraft/world/World;DDD)V 
  at de.ellpeck.naturesaura.blocks.BlockProjectileGenerator$1.func_82499_a(BlockProjectileGenerator.java:52) ~[naturesaura:33.2] 
  at net.minecraft.dispenser.ProjectileDispenseBehavior.func_82487_b(SourceFile:20) ~[?:?] 
  at net.minecraft.dispenser.DefaultDispenseItemBehavior.dispense(SourceFile:15) ~[?:?] 
  at net.minecraft.block.DispenserBlock.func_176439_d(SourceFile:89) ~[?:?] 
  at net.minecraft.block.DispenserBlock.func_225534a(SourceFile:112) ~[?:?] 
  at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227033a(AbstractBlock.java:618) ~[?:?] 
  at net.minecraft.world.server.ServerWorld.func_205338_b(ServerWorld.java:591) ~[?:?] 
  at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:84) ~[?:?] 
  at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:336) ~[?:?] 
  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
```

I think this is related to this code block:
https://github.com/Ellpeck/NaturesAura/blob/84959fbaf7fd1911b0c0db43f6a702057106518d/src/main/java/de/ellpeck/naturesaura/blocks/BlockProjectileGenerator.java#L49-L54

**Comment by Ellpeck** [comment] 2020-12-28 20:44
Duplicate of #170.

**Closed by Ellpeck** 2020-12-28 20:44 UTC
