### ISSUE TITLE
Crash w/Fast Leaf Decay [1.15.2]

### ISSUE THREAD

**Issue by curlywaffles** [Ellpeck/NaturesAura#98] opened 2020-03-29 22:54 UTC
This crash happened once an ancient tree's leaves turned into the decayed version.  Resulted into a continuous CTD on world start up. Unsure if Natures Aura or Fast Leaf Decay problem. The only way to get the world to load back in was remove Fast Leaf Decay entirely.

Crash log: https://pastebin.com/PBHWXedL

Just so happened I was placing a Torchmaster feral flare lantern when it happened. May be unrelated.

Thanks.

**Comment by Quarris** [comment] 2020-03-29 22:55
Duplicate of #78

**Closed** 2020-03-29 22:57 UTC
